# Task 1: Data acquisition and exploration {#sec-data}

## COVID-19

### CNE data

The data published in the [CNE COVID-19 Panel](https://cnecovid.isciii.es/covid19/#distribuci%C3%B3n-geogr%C3%A1fica) offers information related to infections, recoveries and deaths reported by local and regional governments in Spain. It comes from the individualised declaration of COVID-19 cases to the National Epidemiological Surveillance Network (RENAVE) through the SiViEs computer application.

In SiViEs, all reported cases are accounted for, following the surveillance strategy in force at the time (Strategy for early detection, surveillance and control of COVID-19 available at <https://www.mscbs.gob.es/profesionales/saludPublica/ccayes/alertasActual/nCov/documentos/COVID19_Estrategia_vigilancia_y_control_e_indicadores.pdf>

In the current work, we will use two datasets from CNE:

-   casos_tecnica_provincia.csv: Number of cases by diagnostic technique and province (of residence)

-   casos_hosp_uci_def_sexo_edad_provres.csv: Number of hospitalisations, number of admissions to ICU and number of deaths by sex, age and province of residence.


## Mobility data


### INE data

The main objective of the INE dataset is to measure mobility between areas during the period starting in March-2020 and ended in 2021.

The population scope is made up of the mobile telephones of the resident population in Spain of the three main mobile operators. Foreign numbered phones are excluded, usually mobiles in the hands of tourists which operate in Spain while roaming.

Data is available in the Spanish National Institute of Statistics in the following [link](https://www.ine.es/experimental/movilidad/experimental_em4.htm#tablas_resultados). It is also provided a [link](https://www.ine.es/jaxiT3/Tabla.htm?t=48252) for direct access to the download portal via queries.

Data can be downloaded in different formats. We recommend using 'CSV: separado por ;'.


### Google data

The data published at <https://www.google.com/covid19/mobility/?hl=en-GB> offers information related to mobility using the Google ecosystem application services such as Android.

The dataset information is available worldwide. In our case, only the information relating to Spain was extracted.

The Google Mobility Reports aim to provide insights into what has changed in response to policies aimed at combating COVID-19. The reports chart movement trends over time by geography, across different categories of places such as retail and recreation, supermarkets and pharmacies, parks, public transport, workplaces and residential.

Each Community Mobility Report is broken down by location and displays the change in visits to places.

Data provided by Google:

-   Region_Mobility_Report_CSVs.zip contains worldwide information

-   20XX_ES_Region_Mobility_Report.csv contains information for Spain. Note: information is provided by year in separate files.


## Meteorological data

### AEMET data

AEMET's meteorological data are available throug its service [AEMET OpenData](https://www.aemet.es/es/datos_abiertos/AEMET_OpenData).

AEMET OpenData is a REST API developed by AEMET that allows the dissemination and reuse of the Agency's meteorological and climatological information, in the sense indicated in Law 18/2015, of July 9, amending Law 37/2007, of November 16, on the reuse of public sector information.

AEMET OpenData allows free download of the data specified in Annex II of the resolution of December 30, 2015 of AEMET, which establishes the public prices to govern the provision of meteorological and climatological services. This resolution has been published in the BOE No. 4 of January 5, 2016. Also available are the data obtained by AEMET in the framework of the collaboration agreement between the State Research Agency and the State Meteorological Agency regarding Spanish activities in Antarctica. 

In order to access AEMET OpenData, it is necessary to request a free API Key. 


